server:
  port: 9092

spring:
  datasource:
    url: jdbc:postgresql://localhost:32768/qrdb
    username: user
    password: password
  jpa:
    generate-ddl: true

qr:
  api:
    uri: http://localhost:9090/api/generate-qr/param