server:
  port: 9092

spring:
  datasource:
    url: jdbc:postgresql://localhost:32768/qrdb
    username: user
    password: password
  jpa:
    generate-ddl: true
  security:
    user:
      name: qq_user
      password: password
      roles:
        - SERVICE
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:32770/realms/qq


qr:
  api:
    uri: http://localhost:9090/api/generate-qr/param